using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Text;

namespace EasySourceGenerators.Generators;

/// <summary>
/// Builds C# source code for partial method bodies based on the provided <see cref="DataMethodBody"/>.
/// This class consumes only the data model, regardless of how the data was produced
/// (fluent API, attributes, simple execution, etc.).
/// </summary>
internal static class DataMethodBodyBuilders
{
    internal static string BuildMethodSource(
        DataMethodBody body,
        IMethodSymbol partialMethod,
        INamedTypeSymbol containingType)
    {
        return body switch
        {
            DataSimpleReturnBody simple => BuildSimpleReturnSource(simple, partialMethod, containingType),
            DataSwitchBody switchBody => BuildSwitchSource(switchBody, partialMethod, containingType),
            _ => throw new NotSupportedException($"Unsupported method body data type: {body.GetType().Name}")
        };
    }

    private static string BuildSimpleReturnSource(
        DataSimpleReturnBody body,
        IMethodSymbol partialMethod,
        INamedTypeSymbol containingType)
    {
        StringBuilder builder = new();
        AppendNamespaceAndTypeHeader(builder, containingType, partialMethod);

        if (!partialMethod.ReturnsVoid)
        {
            string literal = FormatValueAsCSharpLiteral(body.ReturnValue, partialMethod.ReturnType);
            builder.AppendLine($"        return {literal};");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildSwitchSource(
        DataSwitchBody body,
        IMethodSymbol partialMethod,
        INamedTypeSymbol containingType)
    {
        StringBuilder builder = new();
        AppendNamespaceAndTypeHeader(builder, containingType, partialMethod);

        if (partialMethod.Parameters.Length == 0)
        {
            string fallbackExpression = body.DefaultCase?.Expression ?? "default";
            builder.AppendLine($"        return {fallbackExpression};");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        string switchParameterName = partialMethod.Parameters[0].Name;
        builder.AppendLine($"        switch ({switchParameterName})");
        builder.AppendLine("        {");

        ITypeSymbol? parameterType = partialMethod.Parameters.Length > 0 ? partialMethod.Parameters[0].Type : null;
        foreach (DataSwitchCase switchCase in body.Cases)
        {
            string formattedKey = FormatKeyAsCSharpLiteral(switchCase.Key, parameterType);
            builder.AppendLine($"            case {formattedKey}: return {switchCase.FormattedValue};");
        }

        if (body.DefaultCase != null)
        {
            string defaultStatement = body.DefaultCase.Expression.TrimStart().StartsWith("throw ", StringComparison.Ordinal)
                ? $"            default: {body.DefaultCase.Expression};"
                : $"            default: return {body.DefaultCase.Expression};";
            builder.AppendLine(defaultStatement);
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendNamespaceAndTypeHeader(StringBuilder builder, INamedTypeSymbol containingType, IMethodSymbol partialMethod)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine($"// Generated by {typeof(GeneratesMethodGenerator).FullName} for method '{partialMethod.Name}'.");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine();

        string? namespaceName = containingType.ContainingNamespace?.IsGlobalNamespace == false
            ? containingType.ContainingNamespace.ToDisplayString()
            : null;
        if (namespaceName != null)
        {
            builder.AppendLine($"namespace {namespaceName};");
            builder.AppendLine();
        }

        string typeKeyword = containingType.TypeKind switch
        {
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => "class"
        };

        string typeModifiers = containingType.IsStatic ? "static partial" : "partial";
        builder.AppendLine($"{typeModifiers} {typeKeyword} {containingType.Name}");
        builder.AppendLine("{");

        string accessibility = partialMethod.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "private"
        };

        string returnTypeName = partialMethod.ReturnType.ToDisplayString();
        string methodName = partialMethod.Name;
        string parameters = string.Join(", ", partialMethod.Parameters.Select(parameter => $"{parameter.Type.ToDisplayString()} {parameter.Name}"));
        string methodModifiers = partialMethod.IsStatic ? "static partial" : "partial";

        builder.AppendLine($"    {accessibility} {methodModifiers} {returnTypeName} {methodName}({parameters})");
        builder.AppendLine("    {");
    }

    internal static string FormatValueAsCSharpLiteral(string? value, ITypeSymbol returnType)
    {
        if (value == null)
        {
            return "default";
        }

        return returnType.SpecialType switch
        {
            SpecialType.System_String => SyntaxFactory.Literal(value).Text,
            SpecialType.System_Char when value.Length == 1 => SyntaxFactory.Literal(value[0]).Text,
            SpecialType.System_Boolean => value.ToLowerInvariant(),
            _ when returnType.TypeKind == TypeKind.Enum => $"{returnType.ToDisplayString()}.{value}",
            _ => value
        };
    }

    internal static string FormatKeyAsCSharpLiteral(object key, ITypeSymbol? parameterType)
    {
        if (parameterType?.TypeKind == TypeKind.Enum)
        {
            return $"{parameterType.ToDisplayString()}.{key}";
        }

        return key switch
        {
            bool b => b ? "true" : "false",
            // SyntaxFactory.Literal handles escaping and quoting (e.g. "hello" → "\"hello\"")
            string s => SyntaxFactory.Literal(s).Text,
            _ => key.ToString()!
        };
    }
}
