using EasySourceGenerators.Generators.SourceEmitting;

namespace EasySourceGenerators.GeneratorTests;

[TestFixture]
public class PartialMethodSourceEmitterTests
{
    private static PartialMethodEmitData CreateBasicEmitData(
        string? namespaceName = "TestNamespace",
        string typeName = "MyClass",
        string typeKeyword = "class",
        string typeModifiers = "partial",
        string accessibilityKeyword = "public",
        string methodModifiers = "partial",
        string returnTypeName = "string",
        string methodName = "GetValue",
        string parameterList = "",
        bool returnsVoid = false)
    {
        return new PartialMethodEmitData(
            GeneratorFullName: "TestGenerator",
            NamespaceName: namespaceName,
            TypeName: typeName,
            TypeKeyword: typeKeyword,
            TypeModifiers: typeModifiers,
            AccessibilityKeyword: accessibilityKeyword,
            MethodModifiers: methodModifiers,
            ReturnTypeName: returnTypeName,
            MethodName: methodName,
            ParameterList: parameterList,
            ReturnsVoid: returnsVoid);
    }

    [Test]
    public void Emit_WithReturnValue_ContainsReturnStatement()
    {
        PartialMethodEmitData data = CreateBasicEmitData();

        string result = PartialMethodSourceEmitter.Emit(data, "\"hello\"");

        Assert.That(result, Does.Contain("return \"hello\";"));
    }

    [Test]
    public void Emit_WithNullReturnValue_ReturnsDefault()
    {
        PartialMethodEmitData data = CreateBasicEmitData();

        string result = PartialMethodSourceEmitter.Emit(data, null);

        Assert.That(result, Does.Contain("return default;"));
    }

    [Test]
    public void Emit_VoidReturn_DoesNotContainReturnStatement()
    {
        PartialMethodEmitData data = CreateBasicEmitData(returnTypeName: "void", returnsVoid: true);

        string result = PartialMethodSourceEmitter.Emit(data, null);

        Assert.That(result, Does.Not.Contain("return"));
    }

    [Test]
    public void Emit_ContainsAutoGeneratedHeader()
    {
        PartialMethodEmitData data = CreateBasicEmitData();

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("// <auto-generated/>"));
    }

    [Test]
    public void Emit_ContainsGeneratorNameInComment()
    {
        PartialMethodEmitData data = CreateBasicEmitData(methodName: "MyMethod");

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("TestGenerator"));
        Assert.That(result, Does.Contain("MyMethod"));
    }

    [Test]
    public void Emit_ContainsPragmaWarningDisable()
    {
        PartialMethodEmitData data = CreateBasicEmitData();

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("#pragma warning disable"));
    }

    [Test]
    public void Emit_WithNamespace_ContainsNamespaceDeclaration()
    {
        PartialMethodEmitData data = CreateBasicEmitData(namespaceName: "MyApp.Models");

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("namespace MyApp.Models;"));
    }

    [Test]
    public void Emit_WithoutNamespace_DoesNotContainNamespaceDeclaration()
    {
        PartialMethodEmitData data = CreateBasicEmitData(namespaceName: null);

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Not.Contain("namespace"));
    }

    [Test]
    public void Emit_ContainsTypeDeclaration()
    {
        PartialMethodEmitData data = CreateBasicEmitData(
            typeModifiers: "static partial",
            typeKeyword: "class",
            typeName: "Helper");

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("static partial class Helper"));
    }

    [Test]
    public void Emit_ContainsMethodSignature()
    {
        PartialMethodEmitData data = CreateBasicEmitData(
            accessibilityKeyword: "internal",
            methodModifiers: "static partial",
            returnTypeName: "int",
            methodName: "Calculate",
            parameterList: "int x, string y");

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("internal static partial int Calculate(int x, string y)"));
    }

    [Test]
    public void Emit_ContainsClosingBraces()
    {
        PartialMethodEmitData data = CreateBasicEmitData();

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        // Should end with method closing brace and type closing brace
        Assert.That(result, Does.Contain("    }"));
        Assert.That(result, Does.Contain("}"));
    }

    [Test]
    public void Emit_StructType_ContainsStructKeyword()
    {
        PartialMethodEmitData data = CreateBasicEmitData(typeKeyword: "struct");

        string result = PartialMethodSourceEmitter.Emit(data, "42");

        Assert.That(result, Does.Contain("partial struct MyClass"));
    }
}
