// SwitchCase/SwitchDefault attribute-based generation is commented out pending replacement with a data-driven approach.
// See DataMethodBodyBuilders.cs for details on the planned replacement.

/*
using EasySourceGenerators.Abstractions;
// ReSharper disable ConvertClosureToMethodGroup

namespace EasySourceGenerators.Tests.Generation.Passing;

[TestFixture]
public class BoolSwitchKeyTests
{
    [TestCase(true, "Yes")]
    [TestCase(false, "No")]
    public void BoolSwitchKey_ProducesExpectedRuntimeOutput(bool flag, string expected)
    {
        string result = TestBoolSwitchClass.GetBoolLabel(flag);
        Assert.That(result, Is.EqualTo(expected));
    }

    [Test]
    public void BoolSwitchKey_ProducesExpectedGeneratedCode()
    {
        string generatedCode = GeneratedCodeTestHelper.ReadGeneratedCode("TestBoolSwitchClass_GetBoolLabel.g.cs");
        string expectedCode = """
                              namespace EasySourceGenerators.Tests.Generation.Passing;

                              static partial class TestBoolSwitchClass
                              {
                                  public static partial string GetBoolLabel(bool flag)
                                  {
                                      switch (flag)
                                      {
                                          case true: return "Yes";
                                          case false: return "No";
                                          default: return "Unknown";
                                      }
                                  }
                              }
                              """.ReplaceLineEndings("\n").TrimEnd();

        Assert.That(generatedCode, Is.EqualTo(expectedCode));
    }

    [Test]
    public void BoolSwitchKey_GeneratedCode_HasAutoGeneratedHeaderAndWarningSuppression()
    {
        string generatedCode = GeneratedCodeTestHelper.ReadGeneratedCodeRaw("TestBoolSwitchClass_GetBoolLabel.g.cs");

        Assert.That(generatedCode, Does.StartWith("// <auto-generated/>"));
        Assert.That(generatedCode, Does.Contain("Generated by EasySourceGenerators.Generators.GeneratesMethodGenerator for method 'GetBoolLabel'"));
        Assert.That(generatedCode, Does.Contain("#pragma warning disable"));
    }
}

public static partial class TestBoolSwitchClass
{
    public static partial string GetBoolLabel(bool flag);

    [MethodBodyGenerator(nameof(GetBoolLabel))]
    [SwitchCase(arg1: true)]
    [SwitchCase(arg1: false)]
    static string GetBoolLabel_Generator(bool flag) => flag ? "Yes" : "No";

    [MethodBodyGenerator(nameof(GetBoolLabel))]
    [SwitchDefault]
    static Func<bool, string> GetBoolLabel_Default() => _ => "Unknown";
}
*/
